version: '3.8'
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000
    restart: always


  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_gradio
    ports:
      - "7860:7860"
    restart: always




