stages:
    - test
    - build
    - deploy

run_tests:
    stage: test
    image: python:3.10.8-slim-buster
    before_script:
        - pip install -r requirements.txt
    script:
        - python -m pytest
